
version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez

      - name: product
        identifier: raw_gz_product
        
      - name: ship
        identifier: raw_gz_ship
         
models:
  - name: stg_raw__product
    columns:
      - name: products_id
        tests:
          - unique
          - not_null

  - name: stg_raw__ship
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null